def additoin(x, y):
    print("Addition:", x + b)    
try:
    additoin(10, 20)
except NameError as e:
    print(e)
else:
    print("the operation is successful")

